### PR TITLE
groot: improve perf of reading slices of builtins

### PR DESCRIPTION
**Pull request by sbinet**
```
name                      old time/op    new time/op    delta
ReadTreeSliF64/0-4           660µs ± 3%     217µs ± 3%   -67.14%  (p=0.000 n=20+20)
ReadTreeSliF64/1-4           663µs ± 4%     217µs ± 4%   -67.25%  (p=0.000 n=20+20)
ReadTreeSliF64/2-4           664µs ± 4%     215µs ± 2%   -67.57%  (p=0.000 n=20+19)
ReadTreeSliF64/4-4           669µs ± 3%     217µs ± 3%   -67.52%  (p=0.000 n=19+20)
ReadTreeSliF64/8-4           665µs ± 3%     219µs ± 6%   -67.00%  (p=0.000 n=20+20)
ReadTreeSliF64/16-4          665µs ± 2%     218µs ± 3%   -67.26%  (p=0.000 n=20+20)
ReadTreeSliF64/64-4          664µs ± 3%     216µs ± 2%   -67.47%  (p=0.000 n=20+17)
ReadTreeSliF64/128-4         657µs ± 3%     216µs ± 3%   -67.12%  (p=0.000 n=18+19)
ReadTreeSliF64/512-4         659µs ± 3%     218µs ± 2%   -66.90%  (p=0.000 n=20+20)
ReadTreeSliF64/1024-4        663µs ± 3%     221µs ± 3%   -66.70%  (p=0.000 n=19+19)
ReadTreeSliF64/1048576-4     661µs ± 3%     225µs ± 9%   -65.92%  (p=0.000 n=19+20)

name                      old alloc/op   new alloc/op   delta
ReadTreeSliF64/0-4           396kB ± 0%       0kB ± 0%  -100.00%  (p=0.000 n=19+14)
ReadTreeSliF64/1-4           396kB ± 0%       0kB ± 0%  -100.00%  (p=0.000 n=19+14)
ReadTreeSliF64/2-4           396kB ± 0%       0kB ± 8%  -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/4-4           396kB ± 0%       0kB ± 0%  -100.00%  (p=0.000 n=20+17)
ReadTreeSliF64/8-4           396kB ± 0%       0kB ± 0%  -100.00%  (p=0.000 n=19+15)
ReadTreeSliF64/16-4          396kB ± 0%       0kB ± 0%  -100.00%  (p=0.000 n=20+17)
ReadTreeSliF64/64-4          396kB ± 0%       0kB ± 0%  -100.00%  (p=0.000 n=19+14)
ReadTreeSliF64/128-4         396kB ± 0%       0kB ± 7%  -100.00%  (p=0.000 n=20+18)
ReadTreeSliF64/512-4         396kB ± 0%       0kB ± 0%  -100.00%  (p=0.000 n=20+16)
ReadTreeSliF64/1024-4        396kB ± 0%       0kB ± 0%  -100.00%  (p=0.000 n=20+17)
ReadTreeSliF64/1048576-4     396kB ± 0%       0kB ± 7%  -100.00%  (p=0.000 n=20+18)

name                      old allocs/op  new allocs/op  delta
ReadTreeSliF64/0-4             987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/1-4             987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/2-4             987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/4-4             987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/8-4             987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/16-4            987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/64-4            987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/128-4           987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/512-4           987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/1024-4          987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
ReadTreeSliF64/1048576-4       987 ± 0%         0       -100.00%  (p=0.000 n=20+20)
```

### CODE REVIEW

**Comment by sbinet** [comment]
@rmadar: this is mainly for slices of builtins, flat-trees.
other use-cases might get _some_ improvements from:

- smaller garbage collector pressure
- use of new (slightly better) decompression library.

but as can be seen from the benchmark figures above, varying the length of the slice of `float64` doesn't impact that much the time to read the tree.
this means the biggest overhead comes from actually loading the branches...

**Comment by rmadar** [comment]
Thanks for this! I didn't (yet) benchmark it on slices, but on float branches the improvements is of the order of 15%. I have updated https://github.com/rmadar/perf-gohep . I'll try with a TTree having slices and post the numbers.

**Comment by sbinet** [comment]
this might not be a hard limit:
- better code through better compiler (this happens, from time to time)
- reorganize code a bit
- chase and reduce memory allocations

tap into those idle cores:
- load branches in parallel
- load events in parallel

I am starting to play a bit with this in my `groot-pload` branch.

**Comment by rmadar** [comment]
> I'll try with a TTree having slices and post the numbers.

I have added [there](https://github.com/rmadar/perf-gohep) a fake data generation with 30 branches, either `float64` or `[]float64` over 100 kEvts. I tried default go-hep version and last commit for both cases. I see 20-22% improvement in both cases, so not a larger improvement for slices (their length is randomly distributed between 0 and 30).

It's not impossible that I am doing something wrong but the code looks quite simple (and the generated data look OK).

**Comment by sbinet** [comment]
The numbers I've shown are for a tree with a single slice.

This would still point to a performance issue loading the "multitude" of branches.

**Comment by sbinet** [comment]
I'll look at your cpu profile.

**Comment by sbinet** [comment]
Ah. And you've created your file with compression enabled (the default), whereas I've disabled it to disentangle it from decoding speed.

**Comment by rmadar** [comment]
> Ah. And you've created your file with compression enabled (the default), whereas I've disabled it to disentangle it from decoding speed. 

Ha interesting ...
 1. how can I disable it?
 2. if I do, comparison with ROOT is unfair I guess?

I have added ROOT numbers [here](https://github.com/rmadar/perf-gohep) for vector branches (well `array[N]`) both with `t->Branch()` and `TTreeReader` approaches. Numbers are quite interesting: 
  + `Branch`: 22ms / kEvts
  + `TTreeReader`: **8 ms / kEvts** (here, I suspect - hope - all data are not loaded, just the used one)
  + `go-hep`: 45 ms / kEvts

**Comment by sbinet** [comment]
have a look at my benchmarks:
https://github.com/go-hep/hep/blob/master/groot/rtree/rw_test.go#L1814..L1828

yes comparing groot-no-compression vs ROOT-with-compression would be unfair.
I was just pointing out the origin of the discrepancies b/w your perf numbers and mine.

**Comment by rmadar** [comment]
> `TTreeReader`: **8 ms / kEvts** (here, I suspect - hope - all data are not loaded, just the used one)

Actually, I have modified the test to sum over all vector elements of all branches (to make sure all data are effectively loaded), and the time goes from 8ms to 11ms. So `TTreeReader` is bascially twice faster than `t->Branch()`, which is (currently) twice faster than `rtree.ReadVar`. So I don't how they do, but they are quite fast (maybe they are some ideas to grasp?).

**Pull request merged**
