### PR TITLE
Xrootd marshaler

### PR DESCRIPTION
**Pull request by sbinet**
it's still a WIP.
but gives a general idea of what I think ATM it should look like.
(not sure yet on the `type RequestID uint16` part)

### CODE REVIEW

**Comment by EgorMatirov** [comment]
I'm unsure on the `RequestID` part in the interface too, otherwise it looks good.

**Comment by sbinet** [comment]
example:
```
$> go run ./protocol/gen-marshal.go -p go-hep.org/x/hep/xrootd/protocol/login -t Request
// MarshalXrd implements xrootd/protocol.Marshaler
func (o *Request) MarshalXrd() (data []byte, err error) {
	var buf [8]byte
	binary.BigEndian.PutUint32(buf[:4], uint32(o.Pid))
	data = append(data, buf[:4]...)
	data = append(data, o.Username[:]...)
	data = append(data, byte(o.Reserved))
	data = append(data, byte(o.Ability))
	data = append(data, byte(o.Capabilities))
	data = append(data, byte(o.Role))
	binary.BigEndian.PutUint32(buf[:4], uint32(o.TokenLength))
	data = append(data, buf[:4]...)
	binary.BigEndian.PutUint64(buf[:8], uint64(len(o.Token)))
	data = append(data, buf[:8]...)
	data = append(data, o.Token...)
	return data, err
}

// UnmarshalXrd implements xrootd/protocol.Unmarshaler
func (o *Request) UnmarshalXrd(data []byte) (err error) {
	o.Pid = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	copy(o.Username[:], data[:8])
	data = data[8:]
	o.Reserved = data[0]
	data = data[1:]
	o.Ability = data[0]
	data = data[1:]
	o.Capabilities = data[0]
	data = data[1:]
	o.Role = data[0]
	data = data[1:]
	o.TokenLength = int32(binary.BigEndian.Uint32(data[:4]))
	data = data[4:]
	{
		n := int(binary.BigEndian.Uint32(data[:4]))
		o.Token = make([]byte, n)
		data = data[4:]
		o.Token = append(o.Token, data[:n]...)
		data = data[n:]
	}
	return err
}

```

**Comment by sbinet** [comment]
one possible alternative (because the automatically generated code is a bit hard to read) is to define a `xrootd/protocol.Encoder` type:

```go
type Encoder struct {
	buf []byte
}

func (enc *Encoder) Bytes() []byte { return enc.buf }

func (enc *Encoder) WriteU8(v uint8) {
	enc.buf = append(enc.buf, v)
}

func (enc *Encoder) WriteU16(v uint16) {
	var buf [2]byte
	binary.BigEndian.PutUint16(buf[:], v)
	enc.buf = append(enc.buf, buf[:]...)
}

func (enc *Encoder) WriteI32(v int32) {
	var buf [4]byte
	binary.BigEndian.PutUint32(buf[:], uint32(v))
	enc.buf = append(enc.buf, buf[:]...)
}

func (enc *Encoder) WriteI64(v int64) {
	var buf [8]byte
	binary.BigEndian.PutUint64(buf[:], uint64(v))
	enc.buf = append(enc.buf, buf[:]...)
}

func (enc *Encoder) WriteLen(vs []byte) {
	enc.WriteI32(int32(len(vs)))
}

func (enc *Encoder) WriteBytes(vs []byte) {
	enc.buf = append(enc.buf, vs...)
}

func (enc *Encoder) WriteStr(str string) {
	enc.WriteBytes([]byte(str))
}

func (enc *Encoder) WriteReserved(n int) {
	enc.buf = append(enc.buf, make([]byte, n)...)
}
```

and have the generator generate code in terms of that `Encoder` type. (and the equivalent `Decoder` type for the `UnmarshalXrd`)

so this code:
```go
// -> dirlist.Request

// MarshalXrd implements xrootd/protocol.Marshaler
func (o *Request) MarshalXrd() (data []byte, err error) {
	var buf [8]byte
	data = append(data, o.Reserved[:]...)
	data = append(data, byte(o.Options))
	binary.BigEndian.PutUint32(buf[:4], uint32(len(o.Path)))
	data = append(data, buf[:4]...)
	data = append(data, o.Path...)
	return data, err
}

```

would become:
```go
// MarshalXrd implements xrootd/protocol.Marshaler
func (o *Request) MarshalXrd() (data []byte, err error) {
    var enc protocol.Encoder
    enc.WriteReserved(15)
    enc.WriteU8(byte(o.Options))
    enc.WriteLen(len(o.Path))
    enc.WriteStr(o.Path)
    return enc.Bytes(), nil
}
```

**Comment by EgorMatirov** [comment]
I just went to the exam at the university... 
Wow! Thank you very much!

Have you got a WIP on using `protocol.Encoder` in generator or I can take it from here and continue working on it?

I'm looking forward to giving a try to response unmarshaling this evening!

**Comment by sbinet** [comment]
> I just went to the exam at the university...

hope everything went well.

> Have you got a WIP on using protocol.Encoder in generator or I can take it from here and continue working on it?

feel free to steal or work on top of this branch.
I just wanted to see how it'd work :)

**Comment by EgorMatirov** [comment]
> hope everything went well.

Yeah, thanks! :)

It's still a WIP (sorry, probably it's a messy code, I'll polish it tomorrow): https://github.com/EgorMatirov/hep/commits/xrootd-marshaler,
But I have achieved a point where I can declare a protocol response like that:
```go
type ProtocolInfo struct {
	BinaryProtocolVersion int32
	ServerType            protocol.ServerType         `xrootd:"pos=4,width=4,bit=1"`
	IsManager             bool                        `xrootd:"pos=4,width=4,bit=2"`
	IsServer              bool                        `xrootd:"pos=4,width=4,bit=1"`
	IsMeta                bool                        `xrootd:"pos=4,width=4,bit=256"`
	IsProxy               bool                        `xrootd:"pos=4,width=4,bit=512"`
	IsSupervisor          bool                        `xrootd:"pos=4,width=4,bit=1024"`
	SecurityVersion       byte                        `xrootd:"pos=10,optional"`
	ForceSecurity         bool                        `xrootd:"pos=11,width=1,bit=2,optional"`
	SecurityLevel         protocol.SecurityLevel      `xrootd:"optional"`
	SecurityOverridesSize byte                        `xrootd:"optional"`
	SecurityOverrides     []protocol.SecurityOverride `xrootd:"optional"`
}
```
and leave bit fields, optional fields, and slices of structs handling to the marshalling.

Fo example, `UnmarshalXrd` becomes:
```go
func (o *ProtocolInfo) UnmarshalXrd(data []byte) (pos int, err error) {
	dec := xrdenc.NewDecoder(data)
	o.BinaryProtocolVersion = dec.ReadI32()
	dec.SetPos(4)
	o.ServerType = protocol.ServerType(dec.ReadI32())
	o.ServerType = o.ServerType & 1
	dec.SetPos(4)
	{
		x := dec.ReadI32()
		o.IsManager = x&2 != 0
	}
	dec.SetPos(4)
	{
		x := dec.ReadI32()
		o.IsServer = x&1 != 0
	}
	dec.SetPos(4)
	{
		x := dec.ReadI32()
		o.IsMeta = x&256 != 0
	}
	dec.SetPos(4)
	{
		x := dec.ReadI32()
		o.IsProxy = x&512 != 0
	}
	dec.SetPos(4)
	{
		x := dec.ReadI32()
		o.IsSupervisor = x&1024 != 0
	}
	if len(dec.Bytes()) == 0 {
		goto end
	}
	dec.SetPos(10)
	o.SecurityVersion = dec.ReadU8()
	if len(dec.Bytes()) == 0 {
		goto end
	}
	{
		x := dec.ReadU8()
		o.ForceSecurity = x&2 != 0
	}
	if len(dec.Bytes()) == 0 {
		goto end
	}
	o.SecurityLevel = protocol.SecurityLevel(dec.ReadU8())
	if len(dec.Bytes()) == 0 {
		goto end
	}
	o.SecurityOverridesSize = dec.ReadU8()
	if len(dec.Bytes()) == 0 {
		goto end
	}
	for len(dec.Bytes()) != 0 {
		var x protocol.SecurityOverride
		n, err := x.UnmarshalXrd(dec.Bytes())
		if err != nil {
			return 0, err
		}
		o.SecurityOverrides = append(o.SecurityOverrides, x)
		dec.Skip(n)
	}
end:
	return dec.Pos(), err
}
```

**Comment by sbinet** [comment]
that's some nice generator code that you've got there :)
kudos!

that said, I am not completely sure doing the bit-field stanza inside the (un)marshaling is worth the sophistication.

for example, I feel this:
```go
type ProtocolInfo struct {
	BinaryProtocolVersion int32
	ServerType            protocol.ServerType         `xrootd:"pos=4,width=4,bit=1"`
	IsManager             bool                        `xrootd:"pos=4,width=4,bit=2"`
	IsServer              bool                        `xrootd:"pos=4,width=4,bit=1"`
	IsMeta                bool                        `xrootd:"pos=4,width=4,bit=256"`
	IsProxy               bool                        `xrootd:"pos=4,width=4,bit=512"`
	IsSupervisor          bool                        `xrootd:"pos=4,width=4,bit=1024"`
	SecurityVersion       byte                        `xrootd:"pos=10,optional"`
	ForceSecurity         bool                        `xrootd:"pos=11,width=1,bit=2,optional"`
	SecurityLevel         protocol.SecurityLevel      `xrootd:"optional"`
	SecurityOverridesSize byte                        `xrootd:"optional"`
	SecurityOverrides     []protocol.SecurityOverride `xrootd:"optional"`
}
```

would be as easy to grok like so:
```go
type ProtocolInfo struct {
	BinaryProtocolVersion int32
	ServerType            protocol.ServerType
	Flags                 int32	
	SecurityVersion       byte                        
	ForceSecurity         bool                        
	SecurityLevel         protocol.SecurityLevel
	SecurityOverridesSize byte                       
	SecurityOverrides     []protocol.SecurityOverride
}

func (p *ProtocolInfo) IsServer()  bool { return p.Flags&1 != 0 }
func (p *ProtocolInfo) IsManager() bool { return p.Flags&2 != 0 }
func (p *ProtocolInfo) IsMeta()    bool { return p.Flags&256 != 0 }
```
(CPU is cheap. memory isn't.)

also, modifying the usual unmarshal-ing signature from:
```go
func (Type) UnmarshalXXX([]byte) error { ... }
```
to:
```go
func (Type) UnmarshalXXX([]byte) (int, error) { ... }
```

make it resemble more an `io.Reader`:
```go
type Reader interface {
	Read(p []byte) (n int, err error)
}
```

I understand why you had to modify it.
but (and this ties back to an earlier question of mine during one of the initial PRs) it seems to me all of the Xrd requests have their variable size payload at the end, and only one such variable size payload.
(so knowing that the returned number of bytes read is actually the `len(data)` isn't super useful.)

to me, the generator code would only be a little crutch that helps us generate the bulk of the initial (un)marshaling code, and then we'd modify it if needed: the handling of `string` and `[]byte` (and their semantics+meaning) in the official Xrd specs doesn't seem to be completely rational or regular, so we'd always have to tune it a little bit in the end.

thus, better have a nice `Encoder/Decoder` API that we can use, and nice `xxx.Request/Response` Go types that handle the nitty-gritty details of transforming/converting the raw Xrd wire format to a nice Go type inside the (un)marshaling code :)

that said, you obviously have a deeper knowledge of all the Xrd request/response types, so perhaps I missed something in my initial assessment.

**Comment by EgorMatirov** [comment]
Maybe I went too far with bitwise encoding... :)

But I think, it's useful to have `optional` tag since sometimes there are some optional data. (Btw, I think I found a bug when xrootd server doesn't return cpsize and cptype [spec, pages 63-64](http://xrootd.org/doc/dev45/XRdv310.pdf) if only kxr_compress is passed, despite specification states that info will be returned. I'll fill an issue late.)

> I understand why you had to modify it.
> but (and this ties back to an earlier question of mine during one of the initial PRs) it seems to me all of the Xrd requests have their variable size payload at the end, and only one such variable size payload.
> (so knowing that the returned number of bytes read is actually the len(data) isn't super useful.)

That's useful for parsing slices of structs like:
```go
SecurityOverrides     []protocol.SecurityOverride
```
since it's easier than calculate the size of the type, and we need somehow to move forward `pos` of the decoder.

Do I understand correctly that you suggest to use generated code as a base and then manually edit it to meet all the details? If that's ok (e.g. lacking of easy regeneration of that code) then it makes things easier. :)

**Comment by sbinet** [comment]
> Do I understand correctly that you suggest to use generated code as a base and then manually edit it to meet all the details? If that's ok (e.g. lacking of easy regeneration of that code) then it makes things easier. :)

yes. it's just to jumpstart the whole convertion process, and provide us with a nice initial power boost :)

> That's useful for parsing slices of structs like:
> ```
> SecurityOverrides     []protocol.SecurityOverride
> ```
> since it's easier than calculate the size of the type, and we need somehow to move forward pos of the decoder.

ok.

> But I think, it's useful to have `optional` tag since sometimes there are some optional data.

if we agree that the generator is only meant as an initial aid, having the `optional` tag isn't super useful as a struct-field-tag anymore, as this will be handled inside `UnmarshalXrd`. (but, surely, having a doc string tell it may be optional wouldn't hurt :P)

**Comment by sbinet** [comment]
abandonned in favor of #214

**Pull request closed without merging**
