### PR TITLE
xrootd/internal/mux: migrate from xrootd/mux

### PR DESCRIPTION
**Pull request by sbinet**
Fixes go-hep/hep#197.

### CODE REVIEW

**Comment by sbinet** [comment]
@EgorMatirov I may have to wait for your first `client` package to go in before applying this one (so merging is easier)

**Comment by sbinet** [comment]
FYI, this was automatically generated with `golang.org/x/tools/cmd/gomvpkg`:

```
$> gomvpkg \
 -from go-hep.org/x/hep/xrootd/mux \
 -to   go-hep.org/x/hep/xrootd/internal/mux \
 -vcs_mv_cmd "git mv {{.Src}} {{.Dst}}"
```

**Comment by sbinet** [comment]
@EgorMatirov: can I merge this in? (_ie:_ I don't think it will conflict (too much?) with (a rebased) #195)

**Comment by EgorMatirov** [comment]
@sbinet yep, sounds good.

**Pull request merged**
