### PR TITLE
groot/rtree: implement a Formula interpreter

### PR DESCRIPTION
**Pull request by sbinet**
Fixes go-hep/hep#634.

### CODE REVIEW

**Comment by sbinet** [comment]
@rmadar
would that suit you?

note that only expressions are allowed, _i.e.:_ this wouldn't be allowed:
```go
f, err := reader.Formula(`if br1 { return br2*42 } else { return br3 }`, nil)
```

**Comment by rmadar** [comment]
Yeah that looks good! I didnt see examples in the commit, so i need try it in practice, but from what i understood from the test function, this should be all good!

**Comment by sbinet** [comment]
there is an example :)

- https://github.com/go-hep/hep/pull/639/files#diff-6c7e0358952f3a4b4588a948f2605785R208

**Comment by sbinet** [comment]
(not sure about the performances of this whole thing though... happy to get some feedback on that.)

**Pull request merged**
