### PR TITLE
groot/riofs: fix overlaping blocks w/ big-file mode

### PR DESCRIPTION
**Pull request by sbinet**
TKeys sizes computation was broken for "big files".
The code was indeed changing the `key.rvers` field to indicate
the "big file" mode was enabled, but it wasn't updating the
on-disk size of the TKey (ie: missing 8bytes).

This CL computes the correct size in one-go instead of fixing it
after the facts.

Fixes go-hep/hep#821.

### CODE REVIEW

**Comment by sbinet** [comment]
@rmadar PTAL.

it would seem this fixes it for me.
(in my minimal reproducer at least. I was banging my head against my ill-written C++/ROOT code...)

**Comment by rmadar** [comment]
Thanks a lot! Is there a change that you can merge it to master, so that I can try (more easily, let say)?

**Comment by sbinet** [comment]
theoretically, you can try it out like so:

```
$> cd /some/where
$> git clone git@github.com:sbinet-hep/hep
$> cd ./hep
$> git checkout issue-821

$> cd /your/code
$> cat >> go.mod << EOF

replace go-hep.org/x/hep => /some/where/hep
EOF
```

(I'd rather not merge again something into `master` that isn't really proper :P)

**Comment by rmadar** [comment]
Thanks for giving (again) the git commands (I have written them down this time). I tried and it works for me too!!

**Comment by sbinet** [comment]
cool :)

`git` is a swiss-knife that must be relearned every time one reaches back for it :)

**Comment by sbinet** [comment]
tagged as `v0.28.3`.

**Pull request merged**
