### PR TITLE
joss-paper: first stab

### PR DESCRIPTION
**Pull request by sbinet**
Updates go-hep/hep#87.

### CODE REVIEW

**Comment by sbinet** [comment]
BTW, @go-hep/developers feel free to comment, suggest improvements, etc... :)

**Comment by arfon** [comment]
@sbinet - please take a look at the submission guidelines for [what your paper should contain](http://joss.theoj.org/about#paper_structure). The current text is good but it's very terse - a little additional detail would be great.

**Comment by sbinet** [comment]
@arfon PTAL.
did I miss anything?

**Comment by arfon** [comment]
@sbinet - this looks good, thanks. My only concern with what you have now is that there's a lot of content describing the different packages now which you may get a little push back on during review as we usually expect/ask to see content like this is technical documentation.

**Comment by sbinet** [comment]
ok. well, as for code, removing is always easier :)

thanks!

**Comment by arfon** [comment]
> ok. well, as for code, removing is always easier :)

Ha, yes!

**Pull request merged**
