### PR TITLE
hplot/htex: introduce GoHandler

### PR DESCRIPTION
**Pull request by sbinet**
GoHandler is an asynchronous latex compilation handler.

### CODE REVIEW

**Comment by sbinet** [comment]
@rmadar:
this should address your compilation latency.

**Comment by rmadar** [comment]
Thanks a lot for this! I just tried and this doesn't seem to improve things at all (it even seems to degrade), so there is probably something I miss-use (or just a glitch somewhere):

**without LaTex compilation**
```
 Processing report:
    - 240 histograms filled over 2880 kEvts (4 samples, 15 variables, 4 selections)
    - running time: 4.6 ms/kEvt (00:00:13 for 2880 kEvts)
    - time fraction: 99% (event loop), 1% (plotting)
```

**with LaTex compilation**
```
 Processing report:
    - 240 histograms filled over 2880 kEvts (4 samples, 15 variables, 4 selections)
    - running time: 16.1 ms/kEvt (00:00:46 for 2880 kEvts)
    - time fraction: 28% (event loop), 72% (plotting)
```

I use it like this:
```go
// Create a new styled plot and figure
p := hplot.New(); style.ApplyToPlot(p)
f := hplot.Wrap(p); style.ApplyToFigure(f, ana.CompileLatex)

// Adding stuff to plot
// ...

// Save the output
hplot.Save(f, width, height, "myplot.tex")
```
where `style.ApplyToPlot()` and `style.ApplyToFigure()` are defined [here](https://github.com/rmadar/hplot-style/blob/master/style/style.go).

**Comment by sbinet** [comment]
you need to create one `htex.GoHandler`, shared among all invocations of `hplot.Save(...)`.
you'll probably need to modify `ApplyToFigure` so that it takes an explicit `htex.Handler` value (that is then shared among all `hplot.Fig`s.)

_e.g.:_
```go
var latex htex.Handler = htex.NoopHandler{}
if ana.CompileLatex {
    latex = htex.NewGoHandler(10, "pdflatex")
}

for i := 0; i < nplots; i++ {
    // Create a new styled plot and figure
    p := hplot.New(); style.ApplyToPlot(p)
    f := hplot.Wrap(p); style.ApplyToFigure(f, latex)

    // Adding stuff to plot
    // ...

    // Save the output
    err = hplot.Save(f, width, height, fmt.Sprintf("myplot-%02d.tex", i))
}

if latex, ok := latex.(*htex.GoHandler); ok {
    err = latex.Wait()
    if err != nil {
        log.Fatalf("could not compiler latex document(s): %+v", err)
    }
}
```

**Comment by rmadar** [comment]
Thanks, it works nicely now:
```
 Processing report:
    - 240 histograms filled over 2880 kEvts (4 samples, 15 variables, 4 selections)
    - running time: 5.3 ms/kEvt (00:00:15 for 2880 kEvts)
    - time fraction: 90% (event loop), 10% (plotting)
```

**Comment by rmadar** [comment]
Actually, I have updated my code after the change of {`P`, `Wrap` } to {`Fig`, `Figure`}, and it got quite slow. I am not sure why (I also removed the `latex` argument in `style.ApplyToFigure()` since I pass it directly in the main code). I am still running on 240 histograms filled over 2880 kEvts (4 samples, 15 variables, 4 selections):
   + **tex** without compilation:  5.1 ms/kEvt, 98% (loop), 2% (plot)
   + **tex** & compilation *without* `htex.NewGoHandler`: 19.3 ms/kEvt, 24% (loop), 76% (plot)
   + **tex** & compilation *with* `htex.NewGoHandler`: 9.2 ms/kEvt, 51% (loop), 49% (plot)
   + **pdf**: 7.5 ms/kEvt, 63% (loop), 37% (plot)
   + **png**: 5.6 ms/kEvt, 89% (loop), 11% (plot)

(honestly, there were many changes here and there so I am not 100% sure the numbers quoted in my previous comments are correct. But still, 50% of running time to compile 15 plots is a bit much, no?)

**Comment by sbinet** [comment]
Do you have a somewhat sttyle reproducer that I could play with?

**Comment by rmadar** [comment]
You can checkout https://github.com/rmadar/tree-gonalyzer/commit/ba807a092ad9dd00316c2685951ffdbfa0c573d4 and run with or without latex compilation (right now with `htex.NewGoHandler`):
```bash
cd ana-show/
go run ./main.go        # w/o latex compilation
go run ./main.go -latex # w/ latex compilation
```
Compilation handler can be changed here: https://github.com/rmadar/tree-gonalyzer/blob/master/ana/maker.go#L349

Output format can be changed here: https://github.com/rmadar/tree-gonalyzer/blob/master/ana-show/main.go#L30

(sorry the code is a bit messy while testing around ...)

Running `go run ./main.go -latex` with this commit gives me:
```
Processing report:
    - 300 histograms filled over 3120 kEvts (5 samples, 15 variables, 4 selections)
    - running time: 8.2 ms/kEvt (00:00:25 for 3120 kEvts)
    - time fraction: 44% (event loop), 56% (plotting)
```

**Comment by sbinet** [comment]
ok.

well, I don't think there is anything else `htex.GoHandler` can do.
I played a bit with the number of "in-flight" goroutines (4, 12, ... on my 4-cores laptop).
it didn't help.

I've also looked at the various timings of each plot compilation:
```
$> time ./old-show-stat -latex
2020/04/20 09:58:44 delta: 1.865179578s
2020/04/20 09:58:44 delta: 1.861103998s
2020/04/20 09:58:44 delta: 1.881621358s
2020/04/20 09:58:44 delta: 1.886000303s
2020/04/20 09:58:44 delta: 2.269633099s
2020/04/20 09:58:46 delta: 1.592213334s
2020/04/20 09:58:46 delta: 1.764168614s
2020/04/20 09:58:46 delta: 2.043927528s
2020/04/20 09:58:46 delta: 2.062779027s
2020/04/20 09:58:46 delta: 1.727654251s
2020/04/20 09:58:47 delta: 1.313681368s
2020/04/20 09:58:47 delta: 1.734212888s
2020/04/20 09:58:48 delta: 1.89712289s
2020/04/20 09:58:48 delta: 2.020423274s
2020/04/20 09:58:48 delta: 2.191709965s
2020/04/20 09:58:49 delta: 1.789657065s
2020/04/20 09:58:49 delta: 1.85951351s
2020/04/20 09:58:50 delta: 1.707267674s
2020/04/20 09:58:50 delta: 1.905697715s
2020/04/20 09:58:50 delta: 1.889666536s
2020/04/20 09:58:51 delta: 1.922727769s
2020/04/20 09:58:51 delta: 2.146576723s
2020/04/20 09:58:51 delta: 1.604596369s
2020/04/20 09:58:52 delta: 1.749421559s
2020/04/20 09:58:52 delta: 2.088321908s
2020/04/20 09:58:53 delta: 1.519663848s
2020/04/20 09:58:53 delta: 2.159214805s
2020/04/20 09:58:53 delta: 1.643223866s
2020/04/20 09:58:54 delta: 2.086830704s
2020/04/20 09:58:54 delta: 2.154901962s
2020/04/20 09:58:55 delta: 1.977264116s
2020/04/20 09:58:55 delta: 1.909189334s
2020/04/20 09:58:55 delta: 2.013971893s
2020/04/20 09:58:55 delta: 1.485136975s
2020/04/20 09:58:57 delta: 1.998849527s
2020/04/20 09:58:57 delta: 2.509666571s
2020/04/20 09:58:57 delta: 1.928813796s
2020/04/20 09:58:57 delta: 1.989918724s
2020/04/20 09:58:57 delta: 1.861310131s
2020/04/20 09:58:59 delta: 1.765539761s
2020/04/20 09:59:01 delta: 2.070882849s
2020/04/20 09:59:02 delta: 5.159772086s
2020/04/20 09:59:02 delta: 1.682192529s
2020/04/20 09:59:03 delta: 5.692280348s
2020/04/20 09:59:03 delta: 5.705424455s
2020/04/20 09:59:03 delta: 5.772472736s
2020/04/20 09:59:04 delta: 1.78472865s
2020/04/20 09:59:04 delta: 1.942166457s
2020/04/20 09:59:04 delta: 2.280926177s
2020/04/20 09:59:05 delta: 2.057238983s
2020/04/20 09:59:05 delta: 1.959631747s
2020/04/20 09:59:06 delta: 1.486953033s
2020/04/20 09:59:06 delta: 1.517005912s
2020/04/20 09:59:06 delta: 2.029068675s
2020/04/20 09:59:06 delta: 1.908741943s
2020/04/20 09:59:06 delta: 1.861043794s
2020/04/20 09:59:08 delta: 1.701056122s
2020/04/20 09:59:08 delta: 1.784746113s
2020/04/20 09:59:08 delta: 1.609748701s
2020/04/20 09:59:08 delta: 1.416964723s

 Processing report:
    - 300 histograms filled over 3120 kEvts (5 samples, 15 variables, 4 selections)
    - running time: 12.4 ms/kEvt (00:00:38 for 3120 kEvts)
    - time fraction: 33% (event loop), 67% (plotting)


real	0m38.617s
user	1m51.244s
sys	0m3.399s
```

compared to the "non-concurrency" case:
```
$> time ./no-conc-show-stat -latex
2020/04/20 10:32:06 delta: 777.020482ms
2020/04/20 10:32:06 delta: 821.946492ms
2020/04/20 10:32:07 delta: 818.638549ms
2020/04/20 10:32:08 delta: 806.976479ms
2020/04/20 10:32:09 delta: 746.632454ms
2020/04/20 10:32:09 delta: 764.629941ms
2020/04/20 10:32:10 delta: 924.806977ms
2020/04/20 10:32:11 delta: 745.418824ms
2020/04/20 10:32:12 delta: 588.260687ms
2020/04/20 10:32:12 delta: 584.481895ms
2020/04/20 10:32:13 delta: 587.442676ms
2020/04/20 10:32:14 delta: 584.883734ms
2020/04/20 10:32:14 delta: 814.775943ms
2020/04/20 10:32:15 delta: 807.19642ms
2020/04/20 10:32:16 delta: 801.723186ms
2020/04/20 10:32:17 delta: 837.986373ms
2020/04/20 10:32:18 delta: 759.251617ms
2020/04/20 10:32:18 delta: 755.733655ms
2020/04/20 10:32:19 delta: 753.12377ms
2020/04/20 10:32:20 delta: 754.710676ms
2020/04/20 10:32:21 delta: 764.790498ms
2020/04/20 10:32:21 delta: 789.778006ms
2020/04/20 10:32:22 delta: 761.399402ms
2020/04/20 10:32:23 delta: 792.138847ms
2020/04/20 10:32:24 delta: 743.927993ms
2020/04/20 10:32:24 delta: 745.464407ms
2020/04/20 10:32:25 delta: 786.560097ms
2020/04/20 10:32:26 delta: 743.64471ms
2020/04/20 10:32:27 delta: 792.015456ms
2020/04/20 10:32:28 delta: 830.018516ms
2020/04/20 10:32:28 delta: 793.301711ms
2020/04/20 10:32:29 delta: 800.276291ms
2020/04/20 10:32:30 delta: 747.335475ms
2020/04/20 10:32:31 delta: 798.031974ms
2020/04/20 10:32:32 delta: 752.457318ms
2020/04/20 10:32:32 delta: 747.156641ms
2020/04/20 10:32:33 delta: 797.602233ms
2020/04/20 10:32:34 delta: 801.367339ms
2020/04/20 10:32:35 delta: 839.889683ms
2020/04/20 10:32:36 delta: 848.089545ms
2020/04/20 10:32:38 delta: 2.046336709s
2020/04/20 10:32:40 delta: 2.062312295s
2020/04/20 10:32:42 delta: 2.082097166s
2020/04/20 10:32:44 delta: 2.058358298s
2020/04/20 10:32:45 delta: 809.363392ms
2020/04/20 10:32:45 delta: 797.199703ms
2020/04/20 10:32:46 delta: 799.924137ms
2020/04/20 10:32:47 delta: 812.698446ms
2020/04/20 10:32:48 delta: 855.21622ms
2020/04/20 10:32:49 delta: 814.272933ms
2020/04/20 10:32:50 delta: 853.889539ms
2020/04/20 10:32:50 delta: 813.936211ms
2020/04/20 10:32:51 delta: 670.06167ms
2020/04/20 10:32:52 delta: 732.490744ms
2020/04/20 10:32:53 delta: 670.682231ms
2020/04/20 10:32:53 delta: 669.862584ms
2020/04/20 10:32:54 delta: 794.598975ms
2020/04/20 10:32:55 delta: 756.886211ms
2020/04/20 10:32:56 delta: 752.676903ms
2020/04/20 10:32:56 delta: 755.043099ms

 Processing report:
    - 300 histograms filled over 3120 kEvts (5 samples, 15 variables, 4 selections)
    - running time: 20.6 ms/kEvt (00:01:04 for 3120 kEvts)
    - time fraction: 20% (event loop), 80% (plotting)


real	1m4.404s
user	1m4.738s
sys	0m2.356s
```

we are just hitting Amdahl's law.
law

what could perhaps marginally improve the situation would be to start making the plots *during* the "make-the-histos" phase.
this would require a bit of refactoring in `ana-show`, I think. (or in `analyzer` itself.)
_ie:_ start handling more tasks concurrently (and executing them in parallel), and earlier.
conc

**Pull request merged**
