### PR TITLE
groot/rtree: remove gomacro and Formula

### PR DESCRIPTION
**Pull request by sbinet**
gomacro is currently blowing up all binaries that import "groot/rtree":

```
$> ll root-split-with-gomacro
-rwxr-xr-x 1 binet binet 51352304 May  7 08:48

$> ll root-split-no-gomacro
-rwxr-xr-x 1 binet binet 17795938 May  7 12:01
```

### CODE REVIEW

**Comment by sbinet** [comment]
it's a fall off from cosmos72/gomacro#94

**Comment by sbinet** [comment]
@rmadar hope this won't disturb too much your workflow, but I do plan to merge this one in.

**Comment by rmadar** [comment]
No pb, i'll update my stuffs afterhand

**Comment by rmadar** [comment]
Just to know: what are the expected changes from the user / API point of view?

**Comment by sbinet** [comment]
`rtree.Reader.Formula(...)` would (temporarily?) disappear.

I could make it panic instead, if you prefer.

**Comment by rmadar** [comment]
Ha ok. I did switch to FormulaFunc so no pb on my side. I'll just have to clean the code.

**Comment by sbinet** [comment]
great.

**Pull request merged**
