### PR TITLE
groot/rtree: introduce FormulaFunc

### PR DESCRIPTION
**Pull request by sbinet**
This CL introduces a new way to create Formulae: FormulaFunc.
here is the comparison wrt Formula:

```
## ref: with Formula.
## new: with FormulaFunc.
$> benchstat ref.txt new.txt
name                   old time/op    new time/op    delta
FormulaFunc/f0/Eval-4     346ns ± 2%     238ns ± 2%  -31.30%  (p=0.000 n=18+19)
FormulaFunc/f0/Func-4     346ns ± 3%     230ns ± 2%  -33.50%  (p=0.000 n=19+20)
FormulaFunc/f1/Eval-4     359ns ± 2%     312ns ± 2%  -13.03%  (p=0.000 n=19+17)
FormulaFunc/f1/Func-4     365ns ± 2%     304ns ± 2%  -16.70%  (p=0.000 n=20+19)
FormulaFunc/f2/Eval-4     361ns ± 2%     314ns ± 2%  -13.06%  (p=0.000 n=20+18)
FormulaFunc/f2/Func-4     368ns ± 2%     304ns ± 1%  -17.29%  (p=0.000 n=20+18)
FormulaFunc/f3/Eval-4     384ns ± 2%     313ns ± 2%  -18.63%  (p=0.000 n=17+19)
FormulaFunc/f3/Func-4     386ns ± 1%     306ns ± 2%  -20.78%  (p=0.000 n=16+20)

name                   old alloc/op   new alloc/op   delta
FormulaFunc/f0/Eval-4     72.0B ± 0%     40.0B ± 0%  -44.44%  (p=0.000 n=20+20)
FormulaFunc/f0/Func-4     64.0B ± 0%     40.0B ± 0%  -37.50%  (p=0.000 n=20+20)
FormulaFunc/f1/Eval-4     72.0B ± 0%     48.0B ± 0%  -33.33%  (p=0.000 n=20+20)
FormulaFunc/f1/Func-4     64.0B ± 0%     48.0B ± 0%  -25.00%  (p=0.000 n=20+20)
FormulaFunc/f2/Eval-4     72.0B ± 0%     48.0B ± 0%  -33.33%  (p=0.000 n=20+20)
FormulaFunc/f2/Func-4     64.0B ± 0%     48.0B ± 0%  -25.00%  (p=0.000 n=20+20)
FormulaFunc/f3/Eval-4     72.0B ± 0%     48.0B ± 0%  -33.33%  (p=0.000 n=20+20)
FormulaFunc/f3/Func-4     64.0B ± 0%     48.0B ± 0%  -25.00%  (p=0.000 n=20+20)

name                   old allocs/op  new allocs/op  delta
FormulaFunc/f0/Eval-4      3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=20+20)
FormulaFunc/f0/Func-4      2.00 ± 0%      2.00 ± 0%     ~     (all equal)
FormulaFunc/f1/Eval-4      3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=20+20)
FormulaFunc/f1/Func-4      2.00 ± 0%      2.00 ± 0%     ~     (all equal)
FormulaFunc/f2/Eval-4      3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=20+20)
FormulaFunc/f2/Func-4      2.00 ± 0%      2.00 ± 0%     ~     (all equal)
FormulaFunc/f3/Eval-4      3.00 ± 0%      2.00 ± 0%  -33.33%  (p=0.000 n=20+20)
FormulaFunc/f3/Func-4      2.00 ± 0%      2.00 ± 0%     ~     (all equal)
```

all stats:
```
name                   time/op
Formula/f0/Eval-4      346ns ± 2%
Formula/f0/Func-4      346ns ± 3%
Formula/f1/Eval-4      359ns ± 2%
Formula/f1/Func-4      365ns ± 2%
Formula/f2/Eval-4      361ns ± 2%
Formula/f2/Func-4      368ns ± 2%
Formula/f3/Eval-4      384ns ± 2%
Formula/f3/Func-4      386ns ± 1%
FormulaFunc/f0/Eval-4  243ns ± 2%
FormulaFunc/f0/Func-4  235ns ± 2%
FormulaFunc/f1/Eval-4  315ns ± 0%
FormulaFunc/f1/Func-4  307ns ± 2%
FormulaFunc/f2/Eval-4  316ns ± 2%
FormulaFunc/f2/Func-4  309ns ± 1%
FormulaFunc/f3/Eval-4  317ns ± 2%
FormulaFunc/f3/Func-4  310ns ± 2%

name                   alloc/op
Formula/f0/Eval-4      72.0B ± 0%
Formula/f0/Func-4      64.0B ± 0%
Formula/f1/Eval-4      72.0B ± 0%
Formula/f1/Func-4      64.0B ± 0%
Formula/f2/Eval-4      72.0B ± 0%
Formula/f2/Func-4      64.0B ± 0%
Formula/f3/Eval-4      72.0B ± 0%
Formula/f3/Func-4      64.0B ± 0%
FormulaFunc/f0/Eval-4  40.0B ± 0%
FormulaFunc/f0/Func-4  40.0B ± 0%
FormulaFunc/f1/Eval-4  48.0B ± 0%
FormulaFunc/f1/Func-4  48.0B ± 0%
FormulaFunc/f2/Eval-4  48.0B ± 0%
FormulaFunc/f2/Func-4  48.0B ± 0%
FormulaFunc/f3/Eval-4  48.0B ± 0%
FormulaFunc/f3/Func-4  48.0B ± 0%

name                   allocs/op
Formula/f0/Eval-4       3.00 ± 0%
Formula/f0/Func-4       2.00 ± 0%
Formula/f1/Eval-4       3.00 ± 0%
Formula/f1/Func-4       2.00 ± 0%
Formula/f2/Eval-4       3.00 ± 0%
Formula/f2/Func-4       2.00 ± 0%
Formula/f3/Eval-4       3.00 ± 0%
Formula/f3/Func-4       2.00 ± 0%
FormulaFunc/f0/Eval-4   2.00 ± 0%
FormulaFunc/f0/Func-4   2.00 ± 0%
FormulaFunc/f1/Eval-4   2.00 ± 0%
FormulaFunc/f1/Func-4   2.00 ± 0%
FormulaFunc/f2/Eval-4   2.00 ± 0%
FormulaFunc/f2/Func-4   2.00 ± 0%
FormulaFunc/f3/Eval-4   2.00 ± 0%
FormulaFunc/f3/Func-4   2.00 ± 0%
```

### CODE REVIEW

**Comment by sbinet** [comment]
from https://github.com/go-hep/hep/issues/647#issuecomment-623410102:
> Nice (that was fast!!)! So it seems we can get another 15-30% improvement, meaning roughly twice slower than the direct access via `rtree.ReadVar`. 
>
> There is something I don't understand though: now, there is no more "interpreted" operation, right? >So why don't we get the same time than the `rtreeReadVar`? If you just load branches, and call a go function on it, it should be the same as ... loading branches and calling a go function on the values :) (I guess I am missing something but ...)
> 
> Anyway, it is definitely cool !

I haven't made a detailed analysis but my hypothesis is that we are now hitting the reflect toll gate:
- to locate+load values from the `rtree.ReadVar`
- dereference the `rtree.ReadVar.Value` pointers, copy them and pass the values to the user-provided function
- call the user provided function, get the output
- pass it back to the user

all of this is done via `reflect` to be able to handle all types of input parameters and all types of output values.

when/if "generics" land into Go (perhaps in 1-2 years, see [there](https://go.googlesource.com/proposal/+/master/design/go2draft-contracts.md)), a fair amount of `reflect` code could probably go away from `FormulaFunc`.

**Comment by rmadar** [comment]
OK, I have tested it and it works as expected: we are now at a factor ~2.0-2.3 from the direct reading:
 + `ReadVar`: 3.0 ms/kEvt
 + `Formula`: 8.5 ms/kEvt 
 + `FormulaFunc`: 6.7 ms/kEvt

That's quite a big step wrt the very first shot!

I may have a small suggestion, if that's easy: it would be to print the name of the variable that could not be found (it is useful for dumb user like me!). For now, we have:
```
could not create formulaFunc: 
 rtree: could not create FormulaFunc: 
  rtree: could not find all needed ReadVars
```

**Comment by sbinet** [comment]
should be fixed w/ https://github.com/go-hep/hep/pull/693

**Comment by rmadar** [comment]
I have a question on the way `FormulaFunc` works. Let's assume I want to defined branch-based variable and code-based variable in the same way (for *e.g.*, `"top_pt*3"` or `0.87`). I would do (thanks to a kind of wrapper) something like:

```go
// Case 1
f, err := r.FormulaFunc(
    []string{"top_pt"}),
    func (pt float64) float64 {return pt*3},
)

// Case 2
f, err := r.FormulaFunc(
    []string{},
    func () float64 {return 0.87},
)
```

My question is: do we have some of the expensive `reflect` calls when the slice of strings is empty like in case 2?

**Comment by sbinet** [comment]
I expect the difference between the 2 versions to be minimal.
I don't expect the biggest performance drop to come from the number of arguments (and passing them to the user function) but rather from the call to the user function, through `reflect`.

of course, I may be mistaken :)

**Comment by rmadar** [comment]
OK thanks. After thinking a bit, I just changed my wrapper to return the simple function `f` if not info from the tree is needed, and a `r.FormulaFunc(names, f).Func().(T)` otherwise. It's more clean anyway.

**Pull request merged**
